# This file was automatically generated by Sbtix. Do not edit manually.
{
  "versioning" = [{
      "scalaVersion" = "3.3.7";
      "sbtVersion" = "1.10.7";
    }];
  "repos" = {
    "nix-public" = "";
  };

  "artifacts" = {
    "nix-public/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1-javadoc.jar";
      sha256 = "C570B6A2714A88AE3B77E88FF6C608B9EA516AC8B739EBF4B205D67D07CCFC28";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1-sources.jar";
      sha256 = "E7D07607CF333D0412C97D60BC956627B0966FFD304F2323EE3ABA0D6D6C96DE";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.jar";
      sha256 = "203CEFDFA6C81E6AA84E11F292F29CA97344A3C3BC0293ABEA065CD837592873";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.pom";
      sha256 = "3E0C5721FB26BE732CCDF13DB1C59DFEEE0A6DB269EBCC7507EAD1C763A6108B";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-annotations/2.15.1/jackson-annotations-2.15.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.15.1/jackson-annotations-2.15.1-javadoc.jar";
      sha256 = "F5A9518F20DC1758599D42267D78CF5989DC9EEEE29829A2BBBE9FD642097523";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-annotations/2.15.1/jackson-annotations-2.15.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.15.1/jackson-annotations-2.15.1-sources.jar";
      sha256 = "1AE0A927DF76A331CA0409595A8A84C8E3369F5696E5BC5D5DA06D26A1653DEA";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-annotations/2.15.1/jackson-annotations-2.15.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.15.1/jackson-annotations-2.15.1.jar";
      sha256 = "344C1B343D9819D5DD4395F2507977B91BB2463778CF2EF7B0D01724EC8FFAB2";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-annotations/2.15.1/jackson-annotations-2.15.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.15.1/jackson-annotations-2.15.1.pom";
      sha256 = "0CACB5A8537C72D78E41259D6D7E4F09FFE0F7AF9E86C588536D7F58E837E2E7";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-core/2.12.1/jackson-core-2.12.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.12.1/jackson-core-2.12.1-javadoc.jar";
      sha256 = "F10E6253A03E199040A3C54A60BE2899BD61D43D01D49D8DDB4D6D04EE6C1065";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-core/2.12.1/jackson-core-2.12.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.12.1/jackson-core-2.12.1-sources.jar";
      sha256 = "C985C212836804F22BF69AA8A4D8838DD74AC9FE5A3513120DB4DDFD04574B2E";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-core/2.12.1/jackson-core-2.12.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.12.1/jackson-core-2.12.1.jar";
      sha256 = "CC899CB6EAE0C80B87D590EEA86528797369CC4FEB7B79463207D6BB18F0C257";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-core/2.12.1/jackson-core-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.12.1/jackson-core-2.12.1.pom";
      sha256 = "4D09B42B2ADCFE5CA73F541E42D1E36A8BF483594DF09C43BA8D31EB67E04626";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-core/2.15.1/jackson-core-2.15.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.15.1/jackson-core-2.15.1-javadoc.jar";
      sha256 = "963DF687A314D51E6ECEA44BDA5BCBEA921F9D1A1B1FECD3F1AEFFB29C16D6FE";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-core/2.15.1/jackson-core-2.15.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.15.1/jackson-core-2.15.1-sources.jar";
      sha256 = "8F2D5561CFE1C2C8DE09BC51ACB3B3E31EC884D89273AD30C5CEE30935946C23";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-core/2.15.1/jackson-core-2.15.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.15.1/jackson-core-2.15.1.jar";
      sha256 = "9D984319CC976E85C49F40DA928021ACD2D773E259A9FF9F832EDCDAC6920EED";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-core/2.15.1/jackson-core-2.15.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.15.1/jackson-core-2.15.1.pom";
      sha256 = "7C72AA68AEBDF50CF51010364D85896BA8188D15FBF4EE796F8A0614D613B686";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-databind/2.12.1/jackson-databind-2.12.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.12.1/jackson-databind-2.12.1-javadoc.jar";
      sha256 = "3F56F12A787743E93D1E1B57691DAE196DCEC142D47AE7A6256CCA47923F592A";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-databind/2.12.1/jackson-databind-2.12.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.12.1/jackson-databind-2.12.1-sources.jar";
      sha256 = "C1EDCE07C4C71FD9E3636442457F43DF6A810B26F567638C0EF575B08B91D704";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-databind/2.12.1/jackson-databind-2.12.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.12.1/jackson-databind-2.12.1.jar";
      sha256 = "F2CA3C28EBDED59C98447D51AFE945323DF961540AF66A063C015597AF936AA0";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-databind/2.12.1/jackson-databind-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.12.1/jackson-databind-2.12.1.pom";
      sha256 = "98926399D5072408C20CD63063FBE29CF0923FC5061A3A56D6987F4DFF6FA223";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-databind/2.15.1/jackson-databind-2.15.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.15.1/jackson-databind-2.15.1-javadoc.jar";
      sha256 = "C0BF7A7951483A640B515A52DF9120E36B61CAF5DFEABFA775E00B4F82E3FC4D";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-databind/2.15.1/jackson-databind-2.15.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.15.1/jackson-databind-2.15.1-sources.jar";
      sha256 = "BB5231EF09A8C15F5C97327992CD47832CF3C7EE1F7AD83D4334144F9CFA8150";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-databind/2.15.1/jackson-databind-2.15.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.15.1/jackson-databind-2.15.1.jar";
      sha256 = "C1F0347CE2696C94F531D095CD9EF22E648EC090E9B1C3DEE17938B07A1DF176";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-databind/2.15.1/jackson-databind-2.15.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.15.1/jackson-databind-2.15.1.pom";
      sha256 = "EDC9AF251CB54283C2CB4159DDB33809927F0C8912ED421E2902C2D3AE062184";
    };
    "nix-public/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.15.1/jackson-dataformat-yaml-2.15.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.15.1/jackson-dataformat-yaml-2.15.1-javadoc.jar";
      sha256 = "5795E2BF600B8D05697DB490FE96F8732FC1365EB4DDB3385756ABCF0C3413A8";
    };
    "nix-public/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.15.1/jackson-dataformat-yaml-2.15.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.15.1/jackson-dataformat-yaml-2.15.1-sources.jar";
      sha256 = "D782C643D9B3E02AD4287C2D42C6DED4ACC8CEA3FBDEF209C9F3B6EE72014898";
    };
    "nix-public/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.15.1/jackson-dataformat-yaml-2.15.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.15.1/jackson-dataformat-yaml-2.15.1.jar";
      sha256 = "897F1B3509ADE0E70F1498B83CE410C8428B913B12AE4A7C1A6B0B22438BB182";
    };
    "nix-public/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.15.1/jackson-dataformat-yaml-2.15.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.15.1/jackson-dataformat-yaml-2.15.1.pom";
      sha256 = "AA080187D1427E453F277603F90AA52E125CFB863954E4676CA3C3DCDDE78235";
    };
    "nix-public/com/fasterxml/jackson/dataformat/jackson-dataformats-text/2.15.1/jackson-dataformats-text-2.15.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformats-text/2.15.1/jackson-dataformats-text-2.15.1.pom";
      sha256 = "C4B0A8A67A1C6372207899617796D869F13F51EAEB1AC37FC07A9CA713DA4235";
    };
    "nix-public/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.1/jackson-datatype-jsr310-2.12.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.1/jackson-datatype-jsr310-2.12.1-javadoc.jar";
      sha256 = "18E0CE4BA689DCEAF9353E8D0C8CC7C845569BACB306DB91ABDA5F383E68D58A";
    };
    "nix-public/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.1/jackson-datatype-jsr310-2.12.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.1/jackson-datatype-jsr310-2.12.1-sources.jar";
      sha256 = "B99AE335E94822194AB14DE4DBEE6D6FA75393A1C6788B13A3EAB167E40177A9";
    };
    "nix-public/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.1/jackson-datatype-jsr310-2.12.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.1/jackson-datatype-jsr310-2.12.1.jar";
      sha256 = "B1B34405C980766CCE6C283FDC5039A274EA3B911F097B6807C21E1213B10292";
    };
    "nix-public/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.1/jackson-datatype-jsr310-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.1/jackson-datatype-jsr310-2.12.1.pom";
      sha256 = "F44E4DA4876BB633CEBDB48D15F3D7D6D4F8B3D7DC5AFDBCD4343142B6C5C631";
    };
    "nix-public/com/fasterxml/jackson/jackson-base/2.12.1/jackson-base-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-base/2.12.1/jackson-base-2.12.1.pom";
      sha256 = "93A8C78755A31977508021DBB3883C0DD740A06BB1C67FF4942E096C132419F5";
    };
    "nix-public/com/fasterxml/jackson/jackson-base/2.15.1/jackson-base-2.15.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-base/2.15.1/jackson-base-2.15.1.pom";
      sha256 = "A9D73D7BECBF421174568C382AB1629361180FA96FC041C2CD4A245F6963B09D";
    };
    "nix-public/com/fasterxml/jackson/jackson-bom/2.12.1/jackson-bom-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-bom/2.12.1/jackson-bom-2.12.1.pom";
      sha256 = "083B20A4231BB0516D6E1A08248C9FBCE473583A122A07FD2E0EADEFF6908A38";
    };
    "nix-public/com/fasterxml/jackson/jackson-bom/2.15.1/jackson-bom-2.15.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-bom/2.15.1/jackson-bom-2.15.1.pom";
      sha256 = "C51747D114A597949F81140727D9E6CD63E3F43908F3647EFAA70B19E94DAA4D";
    };
    "nix-public/com/fasterxml/jackson/jackson-parent/2.12/jackson-parent-2.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-parent/2.12/jackson-parent-2.12.pom";
      sha256 = "62AA1C1679ADE09F173DBF1B6C32D35C55E75800238FD5E48F13AA4337C0875B";
    };
    "nix-public/com/fasterxml/jackson/jackson-parent/2.15/jackson-parent-2.15.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-parent/2.15/jackson-parent-2.15.pom";
      sha256 = "6CDF97BC66F389F63E36850D2F552D1216688F8E5A58727D3F6A98EDF8675CDE";
    };
    "nix-public/com/fasterxml/jackson/module/jackson-modules-java8/2.12.1/jackson-modules-java8-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-modules-java8/2.12.1/jackson-modules-java8-2.12.1.pom";
      sha256 = "C67B1D8ADBD06EFCDAC8EEF9EF569787F236E3869B81F86FFFF205EE1B4CB467";
    };
    "nix-public/com/fasterxml/oss-parent/41/oss-parent-41.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/oss-parent/41/oss-parent-41.pom";
      sha256 = "AF650FA4DD400BC5769320BCEF08ED93813F349CABE8213D469ACAFBBD945D8A";
    };
    "nix-public/com/fasterxml/oss-parent/50/oss-parent-50.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/oss-parent/50/oss-parent-50.pom";
      sha256 = "F5DA55DD7B88FB170C46801D17774A652FB2F4581FB5B1D0A5FC86AA182B8577";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-anchorlink/0.62.2/flexmark-ext-anchorlink-0.62.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-anchorlink/0.62.2/flexmark-ext-anchorlink-0.62.2-javadoc.jar";
      sha256 = "EC39DDCC1E789833692D005E28B2A171C88B6D5F372CDC69BA52E56DA2B3AEBD";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-anchorlink/0.62.2/flexmark-ext-anchorlink-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-anchorlink/0.62.2/flexmark-ext-anchorlink-0.62.2-sources.jar";
      sha256 = "F415EE5EB1B098FF3A132A918266277B3E859D150EB7216C418B0959069849F1";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-anchorlink/0.62.2/flexmark-ext-anchorlink-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-anchorlink/0.62.2/flexmark-ext-anchorlink-0.62.2.jar";
      sha256 = "996F33EF589D0AA851E8BC3E0E2A0FAFF1B0447C35A9CD02AC9BEC4C400D7A94";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-anchorlink/0.62.2/flexmark-ext-anchorlink-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-anchorlink/0.62.2/flexmark-ext-anchorlink-0.62.2.pom";
      sha256 = "634797F91CCE886BD226292A875A0BF5340F7AECD5752078253FFEEEBC63B06E";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-autolink/0.62.2/flexmark-ext-autolink-0.62.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-autolink/0.62.2/flexmark-ext-autolink-0.62.2-javadoc.jar";
      sha256 = "9C1545E9C8E8702B4B45FFD1DFAC98411EA8F25C844102C2357612CA74453F0D";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-autolink/0.62.2/flexmark-ext-autolink-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-autolink/0.62.2/flexmark-ext-autolink-0.62.2-sources.jar";
      sha256 = "51F4E031A2FE6D9B49F53F2739615EB10FBBA1D8970DF050B6EEFE42CB72EDBB";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-autolink/0.62.2/flexmark-ext-autolink-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-autolink/0.62.2/flexmark-ext-autolink-0.62.2.jar";
      sha256 = "527D4A294778D7DCC7F309D407EBA0526816CED2D691C51308606B286ABF6573";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-autolink/0.62.2/flexmark-ext-autolink-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-autolink/0.62.2/flexmark-ext-autolink-0.62.2.pom";
      sha256 = "873DEB3513093C7620C90A2271E3EF9E65EB843719E580AE1AE57DDDDB51E888";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-emoji/0.62.2/flexmark-ext-emoji-0.62.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-emoji/0.62.2/flexmark-ext-emoji-0.62.2-javadoc.jar";
      sha256 = "5F1BF734E73CA433F58FACD9E8953201E04BC72D454D81A3F73E0246F8E6473A";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-emoji/0.62.2/flexmark-ext-emoji-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-emoji/0.62.2/flexmark-ext-emoji-0.62.2-sources.jar";
      sha256 = "1D7F1838A05837DCB7A2B30A39DC32B3E044EC2C728D6351D4AF839CEC4B3967";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-emoji/0.62.2/flexmark-ext-emoji-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-emoji/0.62.2/flexmark-ext-emoji-0.62.2.jar";
      sha256 = "DCDEFC2DA8EC742AB81605276EBF300962613499C1196FB87E082BD76BC61789";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-emoji/0.62.2/flexmark-ext-emoji-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-emoji/0.62.2/flexmark-ext-emoji-0.62.2.pom";
      sha256 = "B29AA651151E5CC505C89D6BB6F0BE4B830823FE93B4E8F42037BD155C0419D9";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.62.2/flexmark-ext-gfm-strikethrough-0.62.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.62.2/flexmark-ext-gfm-strikethrough-0.62.2-javadoc.jar";
      sha256 = "4064CED4425134C2CC1DFD18EF753940A314D621378C3BAAFF3C7D3EA73871EB";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.62.2/flexmark-ext-gfm-strikethrough-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.62.2/flexmark-ext-gfm-strikethrough-0.62.2-sources.jar";
      sha256 = "47D40C2254A29DF4F324AE688A8CE7E7A23B370E10B1EB3592C207A91F0653CB";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.62.2/flexmark-ext-gfm-strikethrough-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.62.2/flexmark-ext-gfm-strikethrough-0.62.2.jar";
      sha256 = "A46A7C2ABD5E8F2D6655B7E870408053E0BEB2DD14A5ACEC4F2B18F6E5B1F0CF";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.62.2/flexmark-ext-gfm-strikethrough-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.62.2/flexmark-ext-gfm-strikethrough-0.62.2.pom";
      sha256 = "DEF45689E679E7D82AAD3DF7C2DDEEE8B106D58D9499304EC54A2FE823040B06";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.62.2/flexmark-ext-gfm-tasklist-0.62.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.62.2/flexmark-ext-gfm-tasklist-0.62.2-javadoc.jar";
      sha256 = "0E52416CF5FA06F391274FA11C9F9698C019D37DC56324C97420BBDD0EFC0C7A";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.62.2/flexmark-ext-gfm-tasklist-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.62.2/flexmark-ext-gfm-tasklist-0.62.2-sources.jar";
      sha256 = "D7C7F3773CD5636A0A67A3804A75642F0911A83211E51A2D3E73555CE340EFE6";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.62.2/flexmark-ext-gfm-tasklist-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.62.2/flexmark-ext-gfm-tasklist-0.62.2.jar";
      sha256 = "B97CB3DF6DBD38A32BC1F90A7C81F5B112D8A390984E7A5F9FFF7D83F6E2D2C9";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.62.2/flexmark-ext-gfm-tasklist-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.62.2/flexmark-ext-gfm-tasklist-0.62.2.pom";
      sha256 = "1ACA887B843D6516A70FAB3A66AF5200A5F35E09CEB98F2CA97BA935DAD01F1C";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-ins/0.62.2/flexmark-ext-ins-0.62.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-ins/0.62.2/flexmark-ext-ins-0.62.2-javadoc.jar";
      sha256 = "773FCC15F35E046633480DC8BBC2F049BABE167A3C3D4547831FEA8D158459C4";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-ins/0.62.2/flexmark-ext-ins-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-ins/0.62.2/flexmark-ext-ins-0.62.2-sources.jar";
      sha256 = "65159ECF4262D7A4569D9F36BE4A5E8A65F1E3A6A17CF181D4467444E3CECC7C";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-ins/0.62.2/flexmark-ext-ins-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-ins/0.62.2/flexmark-ext-ins-0.62.2.jar";
      sha256 = "15D217EF8F4D7702DA4C7C11A9FD192EEC3D67E9AB5486344DF95584E73336FA";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-ins/0.62.2/flexmark-ext-ins-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-ins/0.62.2/flexmark-ext-ins-0.62.2.pom";
      sha256 = "5C23C3CB446C70C9F87C63BF65ADC2FE8655B329FB5C088F1828FA285D6E6CC0";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-superscript/0.62.2/flexmark-ext-superscript-0.62.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-superscript/0.62.2/flexmark-ext-superscript-0.62.2-javadoc.jar";
      sha256 = "C6DAD3BFB94B628880CC1A4C43F491E623A7A96AFA5E95AB37E64199C4A7F28D";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-superscript/0.62.2/flexmark-ext-superscript-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-superscript/0.62.2/flexmark-ext-superscript-0.62.2-sources.jar";
      sha256 = "B0C537D203BC5F6D28A476125588DBC44121C6FE3A34458C3F405709A2B74E7F";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-superscript/0.62.2/flexmark-ext-superscript-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-superscript/0.62.2/flexmark-ext-superscript-0.62.2.jar";
      sha256 = "C60FE12C39D48F548EF27BA55221483D76D4FBFC1476F4903414AD5AACD2395F";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-superscript/0.62.2/flexmark-ext-superscript-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-superscript/0.62.2/flexmark-ext-superscript-0.62.2.pom";
      sha256 = "33AD16801947809B4947DE78BEB688CDE1BBACC76E2F170EEB34AEDC705F782B";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-tables/0.62.2/flexmark-ext-tables-0.62.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-tables/0.62.2/flexmark-ext-tables-0.62.2-javadoc.jar";
      sha256 = "1F95F204DA613C4ECF64589C4156DEDA6352936BB75FB40250DBD11915007E25";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-tables/0.62.2/flexmark-ext-tables-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-tables/0.62.2/flexmark-ext-tables-0.62.2-sources.jar";
      sha256 = "1101DFE8752E9419B586748B55934D97F18A91A9DB261C2BE03503B208836A02";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-tables/0.62.2/flexmark-ext-tables-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-tables/0.62.2/flexmark-ext-tables-0.62.2.jar";
      sha256 = "761943D94020B78AC27C89840D9979328FC4CB18CB03AED23EE3B9767BF924B5";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-tables/0.62.2/flexmark-ext-tables-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-tables/0.62.2/flexmark-ext-tables-0.62.2.pom";
      sha256 = "A081EB29B9BE8C254ADB567C69408E330460A69498A212CAB4275EDA57B15569";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-wikilink/0.62.2/flexmark-ext-wikilink-0.62.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-wikilink/0.62.2/flexmark-ext-wikilink-0.62.2-javadoc.jar";
      sha256 = "DB5446A23445C6976707F3D526C3537937CE2C1F41F0EEDAA0CDBA0EE9C5AB98";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-wikilink/0.62.2/flexmark-ext-wikilink-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-wikilink/0.62.2/flexmark-ext-wikilink-0.62.2-sources.jar";
      sha256 = "0DBE35DDE394C3C6E982C51277404E6DC264D3A0BBE0377713F899EE06E8F8E5";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-wikilink/0.62.2/flexmark-ext-wikilink-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-wikilink/0.62.2/flexmark-ext-wikilink-0.62.2.jar";
      sha256 = "370676119E0DB87453FE00D823C5B40172980CB24891EA4FEDACF88EFF909DA3";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-wikilink/0.62.2/flexmark-ext-wikilink-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-wikilink/0.62.2/flexmark-ext-wikilink-0.62.2.pom";
      sha256 = "7C7922E67D47EDE8BF44D7DC5F7043488686BDA70F1F29471027FA2B5AE3D3C5";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.62.2/flexmark-ext-yaml-front-matter-0.62.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.62.2/flexmark-ext-yaml-front-matter-0.62.2-javadoc.jar";
      sha256 = "FCCD321716AD722F4BBC26E0EB1E70E630F055C538D9E403C448AF3E71C8C439";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.62.2/flexmark-ext-yaml-front-matter-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.62.2/flexmark-ext-yaml-front-matter-0.62.2-sources.jar";
      sha256 = "C8EC44D1BF5D054DCA50F3531E90091E387D59B4C4EF3D79CA0A04EDD0DBFA39";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.62.2/flexmark-ext-yaml-front-matter-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.62.2/flexmark-ext-yaml-front-matter-0.62.2.jar";
      sha256 = "D59096960D6C80B29B64D4D9DAC936B2C121D0B11C3E00B3DFCC1329DBC113B1";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.62.2/flexmark-ext-yaml-front-matter-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.62.2/flexmark-ext-yaml-front-matter-0.62.2.pom";
      sha256 = "EB1B60DFABE860E710D0AEA958EB95D03518B444EB392DA11B4116C830328BEA";
    };
    "nix-public/com/vladsch/flexmark/flexmark-java/0.62.2/flexmark-java-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-java/0.62.2/flexmark-java-0.62.2.pom";
      sha256 = "248DB1C4F979FDA7BF21E4A6221428536A191A38128DB4AD8DC6D088DA4F5C22";
    };
    "nix-public/com/vladsch/flexmark/flexmark-jira-converter/0.62.2/flexmark-jira-converter-0.62.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-jira-converter/0.62.2/flexmark-jira-converter-0.62.2-javadoc.jar";
      sha256 = "287C116C35A6D05C98D1DEEFB1A7266D041F7B1870C38688B45F36DDE5CF9A43";
    };
    "nix-public/com/vladsch/flexmark/flexmark-jira-converter/0.62.2/flexmark-jira-converter-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-jira-converter/0.62.2/flexmark-jira-converter-0.62.2-sources.jar";
      sha256 = "9549329D989E14DCB5F7DF7209DE14B03DEC0CE5E80D8F42D4173B15D374AA56";
    };
    "nix-public/com/vladsch/flexmark/flexmark-jira-converter/0.62.2/flexmark-jira-converter-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-jira-converter/0.62.2/flexmark-jira-converter-0.62.2.jar";
      sha256 = "E464FB813D747712E88784ED7459F9E1B1300FB53F8E5DCFEE90220811271512";
    };
    "nix-public/com/vladsch/flexmark/flexmark-jira-converter/0.62.2/flexmark-jira-converter-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-jira-converter/0.62.2/flexmark-jira-converter-0.62.2.pom";
      sha256 = "C7BA32E9B627BC8B9B38AB35122E449ECDC2360985121BF5B1972FAE21F2528B";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-ast/0.62.2/flexmark-util-ast-0.62.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-ast/0.62.2/flexmark-util-ast-0.62.2-javadoc.jar";
      sha256 = "00F5D227AF24E41E0334A4CBF9541A31FF5BB9805BD4926BDE94680F8DB1A61E";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-ast/0.62.2/flexmark-util-ast-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-ast/0.62.2/flexmark-util-ast-0.62.2-sources.jar";
      sha256 = "913C5C558176AE83C15CB0E3AD161BC8870F1A751FC823D275E7B4D8EE48F80E";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-ast/0.62.2/flexmark-util-ast-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-ast/0.62.2/flexmark-util-ast-0.62.2.jar";
      sha256 = "762C1C2B9CEC0CDF53FE1FA1068061265A44F7BC33E672C13F838A697189E434";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-ast/0.62.2/flexmark-util-ast-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-ast/0.62.2/flexmark-util-ast-0.62.2.pom";
      sha256 = "CED8C424A618821EA4FEAC0235BA7E2F9F45EF8C2EA14E27320E912BAD4838BA";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-builder/0.62.2/flexmark-util-builder-0.62.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-builder/0.62.2/flexmark-util-builder-0.62.2-javadoc.jar";
      sha256 = "9EFA210CF07943139623FE1E44D94D897C75114007BEBF60891F316BD77ED554";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-builder/0.62.2/flexmark-util-builder-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-builder/0.62.2/flexmark-util-builder-0.62.2-sources.jar";
      sha256 = "353D15015DCBE11CD78A80634F5E74CC4ACE613196031BF1AE0233AE51A067B6";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-builder/0.62.2/flexmark-util-builder-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-builder/0.62.2/flexmark-util-builder-0.62.2.jar";
      sha256 = "1F3177ABF51B4E26E2BBA994DF4902B392C7336E16DFEE7AB2C492E0685D52F5";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-builder/0.62.2/flexmark-util-builder-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-builder/0.62.2/flexmark-util-builder-0.62.2.pom";
      sha256 = "3A2C7261436990B00A801568D14D3EBD4F63F3D47714B4E4329D9CB2B2AEE863";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-collection/0.62.2/flexmark-util-collection-0.62.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-collection/0.62.2/flexmark-util-collection-0.62.2-javadoc.jar";
      sha256 = "89149B3BD6878D94CF1FA47726C22C55113BC6A625C71577FD32E375A39E06A4";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-collection/0.62.2/flexmark-util-collection-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-collection/0.62.2/flexmark-util-collection-0.62.2-sources.jar";
      sha256 = "52A5F824BFC25186AE5766F8176EE99229A4A0B23AA90EEC8BBE6CC521C417AB";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-collection/0.62.2/flexmark-util-collection-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-collection/0.62.2/flexmark-util-collection-0.62.2.jar";
      sha256 = "59F350F064AEB3D0E01E97FB773FB9701E3605D9DB7A6EB12BCE0686412B3809";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-collection/0.62.2/flexmark-util-collection-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-collection/0.62.2/flexmark-util-collection-0.62.2.pom";
      sha256 = "212B6AF6047438702F91F3BEFD25370A5E7E617502737C383A3E0C29A64F4C97";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-data/0.62.2/flexmark-util-data-0.62.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-data/0.62.2/flexmark-util-data-0.62.2-javadoc.jar";
      sha256 = "8648C1DB83B97F8AFC44EF1A2E799D45F7DBD6B5415D30A561B48C2A1CA6E37E";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-data/0.62.2/flexmark-util-data-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-data/0.62.2/flexmark-util-data-0.62.2-sources.jar";
      sha256 = "9DC0F68AACB067C61D36CD59BDE88A11B6D38D2D2DF774CB6C3A4513C5B6E90E";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-data/0.62.2/flexmark-util-data-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-data/0.62.2/flexmark-util-data-0.62.2.jar";
      sha256 = "4EC42683F8AE51EE8227F3443A54EF0D70D076B593890ABAC24648D93EECC39C";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-data/0.62.2/flexmark-util-data-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-data/0.62.2/flexmark-util-data-0.62.2.pom";
      sha256 = "38CB61557085B16B43BE1FCB88C5C5AB87475452B7F0915A6A2DF8626E242288";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-dependency/0.62.2/flexmark-util-dependency-0.62.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-dependency/0.62.2/flexmark-util-dependency-0.62.2-javadoc.jar";
      sha256 = "009B90BCE807922A50297740C892BFCF7B8F3A3655C60D7881B3964D15F0FF64";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-dependency/0.62.2/flexmark-util-dependency-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-dependency/0.62.2/flexmark-util-dependency-0.62.2-sources.jar";
      sha256 = "402F9AD484F7C883944ECE9D98600493A148D7189E37298CA3E77FAD8A26B69B";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-dependency/0.62.2/flexmark-util-dependency-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-dependency/0.62.2/flexmark-util-dependency-0.62.2.jar";
      sha256 = "582D01D2F3F42A9EA966551B354EDBD6C19DFC70BE74F470BC847DB255DE1367";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-dependency/0.62.2/flexmark-util-dependency-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-dependency/0.62.2/flexmark-util-dependency-0.62.2.pom";
      sha256 = "D81F73FAB2BD41AB40D5279CC652BB0CB6C4F2CFE626241B6F416603A06CCFD6";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-format/0.62.2/flexmark-util-format-0.62.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-format/0.62.2/flexmark-util-format-0.62.2-javadoc.jar";
      sha256 = "095943DA7A45CDA9832A63C71BB796818DA0FBA2501FFA4ED71BF1FF68A99581";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-format/0.62.2/flexmark-util-format-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-format/0.62.2/flexmark-util-format-0.62.2-sources.jar";
      sha256 = "6F518303C29487CEF3FAB94F79D41C67705D50795CA0C4F61DAF44F09DB33F75";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-format/0.62.2/flexmark-util-format-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-format/0.62.2/flexmark-util-format-0.62.2.jar";
      sha256 = "78CED2E678E746A78948CE9469FE95EC78C22D085B0254CCE7F826B40231087F";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-format/0.62.2/flexmark-util-format-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-format/0.62.2/flexmark-util-format-0.62.2.pom";
      sha256 = "F1830E94348E34478E7CF759DBD1B404F815D74DF406707AEEBD130C1AB7FA49";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-html/0.62.2/flexmark-util-html-0.62.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-html/0.62.2/flexmark-util-html-0.62.2-javadoc.jar";
      sha256 = "0C41E30133AC907887CB7B17A981EA431DD41969290265DEA77EF8F2976432BA";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-html/0.62.2/flexmark-util-html-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-html/0.62.2/flexmark-util-html-0.62.2-sources.jar";
      sha256 = "29C813F743A8DACB47308207857F51D308D3204ECF7984E396B0A51C1CA8D079";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-html/0.62.2/flexmark-util-html-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-html/0.62.2/flexmark-util-html-0.62.2.jar";
      sha256 = "377BBF407BC7D7B091ADA9EBA16B058B7E7FA60ED4A3EE3C584C5D514E159786";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-html/0.62.2/flexmark-util-html-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-html/0.62.2/flexmark-util-html-0.62.2.pom";
      sha256 = "370551FB04D87FCA7837D4C4EB49A373A80F1B1D0E799FE54821C42B2FCAA726";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-misc/0.62.2/flexmark-util-misc-0.62.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-misc/0.62.2/flexmark-util-misc-0.62.2-javadoc.jar";
      sha256 = "B61C0ADEB3B51B8F1F36256B972F5AAED451E0F0F2FDFC5A3F28CF8A665943D6";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-misc/0.62.2/flexmark-util-misc-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-misc/0.62.2/flexmark-util-misc-0.62.2-sources.jar";
      sha256 = "D8B98BA7A212CBC5C419DFDA8030B40C5F242F17C85383347FE8FA756BFCCB6B";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-misc/0.62.2/flexmark-util-misc-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-misc/0.62.2/flexmark-util-misc-0.62.2.jar";
      sha256 = "06CEC0698633F875E668B401DBAB208E0F56A5D55F956A993209EFAE6BE45DA6";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-misc/0.62.2/flexmark-util-misc-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-misc/0.62.2/flexmark-util-misc-0.62.2.pom";
      sha256 = "BDE413317F2F2805F40D65E8B17270AEA9C0E87A1B8F4CF56C156256517CC67C";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-options/0.62.2/flexmark-util-options-0.62.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-options/0.62.2/flexmark-util-options-0.62.2-javadoc.jar";
      sha256 = "6FF97B0998C0127031BB84FD9EDB102A7569BEB16785B1D00D9F8BD6F8C10C2E";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-options/0.62.2/flexmark-util-options-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-options/0.62.2/flexmark-util-options-0.62.2-sources.jar";
      sha256 = "7B6310D6A06F3AC972D7AE264A481CA64CFD16EB7D47C437B45D8736E5DB1DC1";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-options/0.62.2/flexmark-util-options-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-options/0.62.2/flexmark-util-options-0.62.2.jar";
      sha256 = "A26573C1FEDB494D2FF06D28DB852D316F4D6FC3B43ED2247AFBACD743D9AE50";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-options/0.62.2/flexmark-util-options-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-options/0.62.2/flexmark-util-options-0.62.2.pom";
      sha256 = "169AC9728A9473567DDA3539628C39D6D55B584B632E8A30B2A735BF1A5F88F9";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-sequence/0.62.2/flexmark-util-sequence-0.62.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-sequence/0.62.2/flexmark-util-sequence-0.62.2-javadoc.jar";
      sha256 = "36193DFCFFBBED09484CF9ADE7F59EB6D1DE64090BDB5E46FC24968C853087FA";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-sequence/0.62.2/flexmark-util-sequence-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-sequence/0.62.2/flexmark-util-sequence-0.62.2-sources.jar";
      sha256 = "0056F66C4D65FEBC3AB820DBDFF9A002156A31FA0F8B3828F6E486051D257D46";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-sequence/0.62.2/flexmark-util-sequence-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-sequence/0.62.2/flexmark-util-sequence-0.62.2.jar";
      sha256 = "6684A0048AD088452419A2871A6516E7FD3013700CB34A71CCA4F9F31A0320C4";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-sequence/0.62.2/flexmark-util-sequence-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-sequence/0.62.2/flexmark-util-sequence-0.62.2.pom";
      sha256 = "4371C3C9E92D4625CAB53BD5D94A1DF4E390B54DE1FE561012C6824B0B834938";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-visitor/0.62.2/flexmark-util-visitor-0.62.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-visitor/0.62.2/flexmark-util-visitor-0.62.2-javadoc.jar";
      sha256 = "ECD3B12859F3046B3DA47F68EB5D51C21E483EBCD9CC0436C107FEAE5D7DC21F";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-visitor/0.62.2/flexmark-util-visitor-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-visitor/0.62.2/flexmark-util-visitor-0.62.2-sources.jar";
      sha256 = "C8FCFC0611720519368C29B84B156044A86A689D05E747E2D03F719CA43E876B";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-visitor/0.62.2/flexmark-util-visitor-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-visitor/0.62.2/flexmark-util-visitor-0.62.2.jar";
      sha256 = "7197BFCFDECA859C2DA2D775F322F98B9FD722CB992760A9678BA4C706EAC982";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-visitor/0.62.2/flexmark-util-visitor-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-visitor/0.62.2/flexmark-util-visitor-0.62.2.pom";
      sha256 = "F1AB51866153FE9EA09BE61CCB6DC22B2CE8B04FE3639A9194F0441FE2B9A3C4";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util/0.62.2/flexmark-util-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util/0.62.2/flexmark-util-0.62.2.jar";
      sha256 = "36BB72A3B57A99FF751190CB538AD553499BD49BC24763C642D58C61E9D5B171";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util/0.62.2/flexmark-util-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util/0.62.2/flexmark-util-0.62.2.pom";
      sha256 = "83672CA119525DF59899400BDE45D19964B05AA34BE976697B64FD48DB6A3D1A";
    };
    "nix-public/com/vladsch/flexmark/flexmark/0.62.2/flexmark-0.62.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark/0.62.2/flexmark-0.62.2-javadoc.jar";
      sha256 = "F53E479B73469C480C526331D081D6AC8A1709F75824A0BF25C8FA15C43F624E";
    };
    "nix-public/com/vladsch/flexmark/flexmark/0.62.2/flexmark-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark/0.62.2/flexmark-0.62.2-sources.jar";
      sha256 = "C22F2C40E16476B822F83B2A966B79C8AF490605822E64FDC884BC9FB9D1DADD";
    };
    "nix-public/com/vladsch/flexmark/flexmark/0.62.2/flexmark-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark/0.62.2/flexmark-0.62.2.jar";
      sha256 = "5EBC1707B86C22C70A0EF7C5B7B38A9361C80B89B6BFD0E17BE39AB0ED3272A6";
    };
    "nix-public/com/vladsch/flexmark/flexmark/0.62.2/flexmark-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark/0.62.2/flexmark-0.62.2.pom";
      sha256 = "38E4E8246F49623F6788AB188D2500FEDABCC235D411ED3F25D94DE18BF9CEC8";
    };
    "nix-public/nl/big-o/liqp/0.8.2/liqp-0.8.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/nl/big-o/liqp/0.8.2/liqp-0.8.2-javadoc.jar";
      sha256 = "528F471362AECA484B98191344EDCA12816455987C4C0E0DDF6B58F20B7F5DC8";
    };
    "nix-public/nl/big-o/liqp/0.8.2/liqp-0.8.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/nl/big-o/liqp/0.8.2/liqp-0.8.2-sources.jar";
      sha256 = "C3D1225F1ED152B979E9D43C76B8421ABBC7FBC424D1B57286C3040E8EDE59AC";
    };
    "nix-public/nl/big-o/liqp/0.8.2/liqp-0.8.2.jar" = {
      url = "https://repo1.maven.org/maven2/nl/big-o/liqp/0.8.2/liqp-0.8.2.jar";
      sha256 = "A948C26558E31FB445B5F1A2561C4518136A5D74046E4AB12BFB6010F6B0CC5B";
    };
    "nix-public/nl/big-o/liqp/0.8.2/liqp-0.8.2.pom" = {
      url = "https://repo1.maven.org/maven2/nl/big-o/liqp/0.8.2/liqp-0.8.2.pom";
      sha256 = "846DA39098C20BE8631523C62928E4DD2B4CF7686D428678AAE50060EEF009B8";
    };
    "nix-public/org/antlr/antlr4-master/4.7.2/antlr4-master-4.7.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/antlr/antlr4-master/4.7.2/antlr4-master-4.7.2.pom";
      sha256 = "BA99CB25D2390F38680C7502842A0EE0959D1E6403E013CCFF698FD5856EEAD1";
    };
    "nix-public/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2-javadoc.jar";
      sha256 = "9EC39228BAEECF6FA47493D1C7FBECAE082D53DC474548DED27AB4C36DE2093D";
    };
    "nix-public/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2-sources.jar";
      sha256 = "6290B44CC5ABAAE2D747C966704E80CDFD742B4E2E0C8F9597F84A550E0D7F47";
    };
    "nix-public/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2.jar";
      sha256 = "4C518B87D4BDFF8B44CD8CBC1AF816E944B62A3FE5B80B781501CF1F4759BBC4";
    };
    "nix-public/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2.pom";
      sha256 = "DC09CBA98C25D3C06E4AEC516885D4C3AF03062BA55F4FE6283FC9CF176A60FB";
    };
    "nix-public/org/jetbrains/annotations/15.0/annotations-15.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/jetbrains/annotations/15.0/annotations-15.0-javadoc.jar";
      sha256 = "DC83A61021F46BF4A3773A10DBB948A796CAE6E58064E19B930AB67A9D8DBF44";
    };
    "nix-public/org/jetbrains/annotations/15.0/annotations-15.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/jetbrains/annotations/15.0/annotations-15.0-sources.jar";
      sha256 = "5AB01A68DB908FA869038E1F30F3F6C31E6D90115142F24CED767F9BB7E845E0";
    };
    "nix-public/org/jetbrains/annotations/15.0/annotations-15.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/jetbrains/annotations/15.0/annotations-15.0.jar";
      sha256 = "D74599CEF2B363FDB3CDD3198515ACA090E3EA3E98B2BA473C6E46F114DAB272";
    };
    "nix-public/org/jetbrains/annotations/15.0/annotations-15.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/jetbrains/annotations/15.0/annotations-15.0.pom";
      sha256 = "6726678AC07B481B5E35D3AEEFCE526B95FD18EDE33D0D85CB1C688BCDF0E840";
    };
    "nix-public/org/jline/jline-native/3.29.0/jline-native-3.29.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-native/3.29.0/jline-native-3.29.0-javadoc.jar";
      sha256 = "8DAC9F79234761C60195315CD56E768AE097300E60A84FE1DCF8841DD836187D";
    };
    "nix-public/org/jline/jline-native/3.29.0/jline-native-3.29.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-native/3.29.0/jline-native-3.29.0-sources.jar";
      sha256 = "6CDD8EDF54142ABC558916DF1372A93B115B823DF10FF5C05C11B988A66B2868";
    };
    "nix-public/org/jline/jline-native/3.29.0/jline-native-3.29.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-native/3.29.0/jline-native-3.29.0.jar";
      sha256 = "19CFCC9D3C78A1C6CFE4C6C9599F16A657E4BF8DA43940FC4B875373236DC258";
    };
    "nix-public/org/jline/jline-native/3.29.0/jline-native-3.29.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-native/3.29.0/jline-native-3.29.0.pom";
      sha256 = "5825548C79A919B6B1D8B7C0904BE72A1DE43E84AB5525923C2F91279F38DC83";
    };
    "nix-public/org/jline/jline-parent/3.29.0/jline-parent-3.29.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-parent/3.29.0/jline-parent-3.29.0.pom";
      sha256 = "7922EFD3D870A7D7AE03B196C300E35C5DE0228E59A5B012AEA641E36D79928E";
    };
    "nix-public/org/jline/jline-reader/3.29.0/jline-reader-3.29.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-reader/3.29.0/jline-reader-3.29.0-javadoc.jar";
      sha256 = "E315B83325BAFA927D2A7554E718525C05DB3B6E4C14DBC77695658CA99102F9";
    };
    "nix-public/org/jline/jline-reader/3.29.0/jline-reader-3.29.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-reader/3.29.0/jline-reader-3.29.0-sources.jar";
      sha256 = "F22E92B22A17F16EC8427FDC42ED9C0CAAEFAADDAA35ED9BCC7A396D3E751B1D";
    };
    "nix-public/org/jline/jline-reader/3.29.0/jline-reader-3.29.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-reader/3.29.0/jline-reader-3.29.0.jar";
      sha256 = "A4CB0A5FDE9289F2F1B614E04F94B202F6FF5C9C96476425837B1184C92EF81D";
    };
    "nix-public/org/jline/jline-reader/3.29.0/jline-reader-3.29.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-reader/3.29.0/jline-reader-3.29.0.pom";
      sha256 = "D722F49A91292CFC69DA0E33A61B788DD4253E8174161639F640B21D461CC429";
    };
    "nix-public/org/jline/jline-terminal-jni/3.29.0/jline-terminal-jni-3.29.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal-jni/3.29.0/jline-terminal-jni-3.29.0-javadoc.jar";
      sha256 = "7D7EE19AA4FC4811154A2E6815562F541467A8389281F3B2FF51ED186F037FD5";
    };
    "nix-public/org/jline/jline-terminal-jni/3.29.0/jline-terminal-jni-3.29.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal-jni/3.29.0/jline-terminal-jni-3.29.0-sources.jar";
      sha256 = "C0C0C46D1722873467FD6A0E45A664DFEF27156F4E62A300DBB4545F618B87B9";
    };
    "nix-public/org/jline/jline-terminal-jni/3.29.0/jline-terminal-jni-3.29.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal-jni/3.29.0/jline-terminal-jni-3.29.0.jar";
      sha256 = "13FEF8BCC0E4788C8E192DC76C33758683C6BFDBAEF6F67B41445EB8986773AD";
    };
    "nix-public/org/jline/jline-terminal-jni/3.29.0/jline-terminal-jni-3.29.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal-jni/3.29.0/jline-terminal-jni-3.29.0.pom";
      sha256 = "4DBEC22363D2FA1C4E2C89212F2626BC37F8D52D4DC43E8D87DF77AC64FFAFA4";
    };
    "nix-public/org/jline/jline-terminal/3.29.0/jline-terminal-3.29.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal/3.29.0/jline-terminal-3.29.0-javadoc.jar";
      sha256 = "49C3A5628D608096D715627168C727D1DD9FB1FAE26F3B2A33AA6E5D25F0F049";
    };
    "nix-public/org/jline/jline-terminal/3.29.0/jline-terminal-3.29.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal/3.29.0/jline-terminal-3.29.0-sources.jar";
      sha256 = "44899935C84500C3373DB4F8870C7A40D2DC69515264F8362531FC8C060CEA50";
    };
    "nix-public/org/jline/jline-terminal/3.29.0/jline-terminal-3.29.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal/3.29.0/jline-terminal-3.29.0.jar";
      sha256 = "FD68A98B32B1132035C62102E5DF0B0FDC358E7C87A9F876CE7071450B4D10DA";
    };
    "nix-public/org/jline/jline-terminal/3.29.0/jline-terminal-3.29.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal/3.29.0/jline-terminal-3.29.0.pom";
      sha256 = "7BFA6055D005E2C8FE4A6EFC692AE6EFD7F543E3940FB55ECCA09D58C78CB0FE";
    };
    "nix-public/org/jsoup/jsoup/1.14.2/jsoup-1.14.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.14.2/jsoup-1.14.2-javadoc.jar";
      sha256 = "BDBD84A9CD843B17CE2887F6A1CD973C692772E381B870F8792A77631D733A6A";
    };
    "nix-public/org/jsoup/jsoup/1.14.2/jsoup-1.14.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.14.2/jsoup-1.14.2-sources.jar";
      sha256 = "C4A9E9AA27494649AA0C73289F4AE00B6F83BDDBF0050349B390D0E67BFA7581";
    };
    "nix-public/org/jsoup/jsoup/1.14.2/jsoup-1.14.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.14.2/jsoup-1.14.2.jar";
      sha256 = "A601BA7CE2E2C6E744D4EAC793A76707C0121576170EF717EF7A81F2343ADA1A";
    };
    "nix-public/org/jsoup/jsoup/1.14.2/jsoup-1.14.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.14.2/jsoup-1.14.2.pom";
      sha256 = "DEF87047A7F3BA4817B256AC9361725865104DBE8AA5CC967068313B136D431A";
    };
    "nix-public/org/jsoup/jsoup/1.17.2/jsoup-1.17.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.17.2/jsoup-1.17.2-javadoc.jar";
      sha256 = "E45D0C9EA9A1E71155762DF6B54020A3A452DE6F057AAFD9159FC64390DF9FC3";
    };
    "nix-public/org/jsoup/jsoup/1.17.2/jsoup-1.17.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.17.2/jsoup-1.17.2-sources.jar";
      sha256 = "D108C67F7A3F0A352CB719D5D08105DA934A170A9B5AA576BC1B48C26961488A";
    };
    "nix-public/org/jsoup/jsoup/1.17.2/jsoup-1.17.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.17.2/jsoup-1.17.2.jar";
      sha256 = "F60B33B38E9D7AC93EAAA68A6C70F706BB99036494B2E2ADD2BFEE11D09AC6F5";
    };
    "nix-public/org/jsoup/jsoup/1.17.2/jsoup-1.17.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.17.2/jsoup-1.17.2.pom";
      sha256 = "7A349D217790C3730BE308CED1EA9EE32C4E74F72058E83C2B60E5A28954DD0D";
    };
    "nix-public/org/junit/junit-bom/5.9.2/junit-bom-5.9.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/junit/junit-bom/5.9.2/junit-bom-5.9.2.pom";
      sha256 = "2ED07D65845131F5336A86476C9A4056B59D0B58B9815AB3679BB0F36F35F705";
    };
    "nix-public/org/nibor/autolink/autolink/0.6.0/autolink-0.6.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/nibor/autolink/autolink/0.6.0/autolink-0.6.0-javadoc.jar";
      sha256 = "57C8C2132370DFC455FE19D67E2958A3C75A2634CF97D9B4166B110C65A6391D";
    };
    "nix-public/org/nibor/autolink/autolink/0.6.0/autolink-0.6.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/nibor/autolink/autolink/0.6.0/autolink-0.6.0-sources.jar";
      sha256 = "26D6FBA888C9E332F6357773EF0500A7552C2453779A7D3E5D163E079546D8A8";
    };
    "nix-public/org/nibor/autolink/autolink/0.6.0/autolink-0.6.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/nibor/autolink/autolink/0.6.0/autolink-0.6.0.jar";
      sha256 = "A80BE030F6386F18111CAD9161C0B6983157352A1B59A59E6002172F0D321C04";
    };
    "nix-public/org/nibor/autolink/autolink/0.6.0/autolink-0.6.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/nibor/autolink/autolink/0.6.0/autolink-0.6.0.pom";
      sha256 = "916755647A34CCB367E11834D28380198C834ADFCF660E0D983E375B8F5C28F2";
    };
    "nix-public/org/scala-lang/modules/scala-asm/9.8.0-scala-1/scala-asm-9.8.0-scala-1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/9.8.0-scala-1/scala-asm-9.8.0-scala-1-javadoc.jar";
      sha256 = "EFFFDBCED2084BAB03AB7CD2E13100AFD8080E9638D88E17FC19F7B80DE2C96E";
    };
    "nix-public/org/scala-lang/modules/scala-asm/9.8.0-scala-1/scala-asm-9.8.0-scala-1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/9.8.0-scala-1/scala-asm-9.8.0-scala-1-sources.jar";
      sha256 = "78543AB8BAFEC0E7D09227872DB06F4C725F5E0743F1F3EAB1F60EF6876588E9";
    };
    "nix-public/org/scala-lang/modules/scala-asm/9.8.0-scala-1/scala-asm-9.8.0-scala-1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/9.8.0-scala-1/scala-asm-9.8.0-scala-1.jar";
      sha256 = "86AF037580BDF9CE9C05F8B2AFD734DAF1A8564C38CD10CA5D08BF81508AD2E4";
    };
    "nix-public/org/scala-lang/modules/scala-asm/9.8.0-scala-1/scala-asm-9.8.0-scala-1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/9.8.0-scala-1/scala-asm-9.8.0-scala-1.pom";
      sha256 = "BF9866236DE05DA6F67BF15B94CF65832F9DBBB6B4A3A98BD963E75A234F8D90";
    };
    "nix-public/org/scala-lang/modules/scala-xml_3/2.0.0/scala-xml_3-2.0.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_3/2.0.0/scala-xml_3-2.0.0-javadoc.jar";
      sha256 = "38A48D6CD769608540896E08B6474AB7202C67926909F513704060D6E7E525C8";
    };
    "nix-public/org/scala-lang/modules/scala-xml_3/2.0.0/scala-xml_3-2.0.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_3/2.0.0/scala-xml_3-2.0.0-sources.jar";
      sha256 = "7B9AD53F7CD785364DC8B4E2BE73EC92F5BB6F954411086B24A57C8AFDE29F1F";
    };
    "nix-public/org/scala-lang/modules/scala-xml_3/2.0.0/scala-xml_3-2.0.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_3/2.0.0/scala-xml_3-2.0.0.jar";
      sha256 = "98485486EC710AC1851491D318A31BCEEF372935BC468431C0BC8AFF36401EF7";
    };
    "nix-public/org/scala-lang/modules/scala-xml_3/2.0.0/scala-xml_3-2.0.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_3/2.0.0/scala-xml_3-2.0.0.pom";
      sha256 = "EBBD47D2248D7F4E8616C2EDD05A7F361506E85737D9826DC43D1DB84D08DAD0";
    };
    "nix-public/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16-javadoc.jar";
      sha256 = "97F4264F4B5B5377D29A79A3B098BEC4DDB0A855BC57B66071F1E99BCFAB25FB";
    };
    "nix-public/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16-sources.jar";
      sha256 = "C02EDC324E7DB59C52115214A6EF36E2D78D0A50DFF635EDA4DCEE5502B1DEA5";
    };
    "nix-public/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16.jar";
      sha256 = "1EBB2B6F9E4EB4022497C19B1E1E825019C08514F962AAAC197145F88ED730F1";
    };
    "nix-public/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16.pom";
      sha256 = "B25B72BA96EB30934868D86D307298D24D3AC154D362E7A4EEB37BA51BA86853";
    };
    "nix-public/org/scala-lang/scala-library/2.13.5/scala-library-2.13.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.5/scala-library-2.13.5-javadoc.jar";
      sha256 = "A067CF9DE859FD1E6DD56541F95431E4C37D71BFE5E9EEF2E5276DD05FF8B2FD";
    };
    "nix-public/org/scala-lang/scala-library/2.13.5/scala-library-2.13.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.5/scala-library-2.13.5-sources.jar";
      sha256 = "D7B00DEDCA0CC7AE11FA32CAE24D4059301164B0699C01940B0F21FDF69676C3";
    };
    "nix-public/org/scala-lang/scala-library/2.13.5/scala-library-2.13.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.5/scala-library-2.13.5.jar";
      sha256 = "52AAFEEF8E0D104433329B1BC31463D1B4A9E2B8F24F85432C8CFAED9FAD2587";
    };
    "nix-public/org/scala-lang/scala-library/2.13.5/scala-library-2.13.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.5/scala-library-2.13.5.pom";
      sha256 = "8A83D05DC350A4DD7396BBB632EEBA46833A852B79893DC8946BBC33C614D4E2";
    };
    "nix-public/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8-javadoc.jar";
      sha256 = "5D6362FFC5A4DC73E4AA839636A226E56EE371C1658480A307C8104CAF3CC9B2";
    };
    "nix-public/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8-sources.jar";
      sha256 = "FCFBDB5FA409A10C0B0AF775382D19CD648663E325A6CD5212F0FED00AF31824";
    };
    "nix-public/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.jar";
      sha256 = "A0882B82514190C2BAC7D1A459872A75F005FC0F3E88B2BC0390367146E35DB7";
    };
    "nix-public/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.pom";
      sha256 = "4AE70B3CB0C215D69AEAC28C9212E6811F9EB978956782340608933420880D52";
    };
    "nix-public/org/scala-lang/scala3-compiler_3/3.3.7/scala3-compiler_3-3.3.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.3.7/scala3-compiler_3-3.3.7-javadoc.jar";
      sha256 = "461AE319AD37FB951426B0AEF3550BA13A578BBF0DE8D50B90C014308390854C";
    };
    "nix-public/org/scala-lang/scala3-compiler_3/3.3.7/scala3-compiler_3-3.3.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.3.7/scala3-compiler_3-3.3.7-sources.jar";
      sha256 = "F0C43B55C79A02D013C37AB5B5BC0C74E7A92C6A237A400C7C025312075AD0BB";
    };
    "nix-public/org/scala-lang/scala3-compiler_3/3.3.7/scala3-compiler_3-3.3.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.3.7/scala3-compiler_3-3.3.7.jar";
      sha256 = "E15FED89FB45248550C8227EA407C0EB496A6AFB7BDF7ABBA4285D2FE55BAF44";
    };
    "nix-public/org/scala-lang/scala3-compiler_3/3.3.7/scala3-compiler_3-3.3.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.3.7/scala3-compiler_3-3.3.7.pom";
      sha256 = "812F147809FD8147349A33ADFDBB164A0C74A75EF0E9AEF97B0987AB5036990A";
    };
    "nix-public/org/scala-lang/scala3-interfaces/3.3.7/scala3-interfaces-3.3.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.3.7/scala3-interfaces-3.3.7-javadoc.jar";
      sha256 = "D653AADE571393B17CF4BF5157A64EBBA0F2D6F2909254CD0E120159E52AECC6";
    };
    "nix-public/org/scala-lang/scala3-interfaces/3.3.7/scala3-interfaces-3.3.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.3.7/scala3-interfaces-3.3.7-sources.jar";
      sha256 = "E2376FDC50C23FD5784971B807060C04DBEA4807E5378A2C8C3DD82F8D29896D";
    };
    "nix-public/org/scala-lang/scala3-interfaces/3.3.7/scala3-interfaces-3.3.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.3.7/scala3-interfaces-3.3.7.jar";
      sha256 = "F57F897043EFDA83576B5C18CE01DF5A5A1C2033EEB26224FC2A8D1FB779F82C";
    };
    "nix-public/org/scala-lang/scala3-interfaces/3.3.7/scala3-interfaces-3.3.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.3.7/scala3-interfaces-3.3.7.pom";
      sha256 = "ABEAE521DE55BC164A1AD01B3EA284A5D9D969FBDAE3E4AE1B63C0430459AD59";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0-javadoc.jar";
      sha256 = "2691EF1145EC68EAA0C9ED004C5A1E928443EC2E7867FC0A583348956C8A994F";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0-sources.jar";
      sha256 = "227C194B6AE5D38F4B3E10567279F5CC66AD49EE713081F4CE258998509D1166";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0.jar";
      sha256 = "1AF055A657BEBD47D82E8825BB58A9C7602BEE0E6F041DDF38A177E9FDB5626B";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0.pom";
      sha256 = "A7A6831F32F0662C449AABE7DC9B98BF653BAF311FAB2020E565CA5D73E9BB94";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.1.2/scala3-library_3-3.1.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.1.2/scala3-library_3-3.1.2-javadoc.jar";
      sha256 = "77F640FB06DB16838EEBDF2F3E7653AFC9450D1EC0ED8A377BAC4FFD27924A77";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.1.2/scala3-library_3-3.1.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.1.2/scala3-library_3-3.1.2-sources.jar";
      sha256 = "76DC9BDCC4ECC55B99FBA878B8139C8F2D468BB53D27862EE516E68FF3B5A1C8";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.1.2/scala3-library_3-3.1.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.1.2/scala3-library_3-3.1.2.jar";
      sha256 = "59033127F3432A2F85B04BB6E01EAA1BDF94AD6B1C7652996FDDC9053926AA0B";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.1.2/scala3-library_3-3.1.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.1.2/scala3-library_3-3.1.2.pom";
      sha256 = "2FFE5F617BA9DF06A3EBF8861AD4C46C205AACF5FEAEEA3BDA2371273042B50B";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.3.7/scala3-library_3-3.3.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.3.7/scala3-library_3-3.3.7-javadoc.jar";
      sha256 = "FE4586023AB4EA240BF3872FC9CEEDE80F7721F45ECB953AF977B9D4F06E205C";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.3.7/scala3-library_3-3.3.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.3.7/scala3-library_3-3.3.7-sources.jar";
      sha256 = "D06C4573324F048C6E4F0526DA6B63753F20102BE1FC8C752C97E3BB6B0E80C2";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.3.7/scala3-library_3-3.3.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.3.7/scala3-library_3-3.3.7.jar";
      sha256 = "A16E046F4A9DF9E0D0E0BC54BF6298C94D7D867457F7B3B68291A88C568B92D0";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.3.7/scala3-library_3-3.3.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.3.7/scala3-library_3-3.3.7.pom";
      sha256 = "992BB5414F5855DA7884134EB518D5F700E2849E8F3C4D5164E5C4215EBA2151";
    };
    "nix-public/org/scala-lang/scala3-sbt-bridge/3.3.7/scala3-sbt-bridge-3.3.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-sbt-bridge/3.3.7/scala3-sbt-bridge-3.3.7-javadoc.jar";
      sha256 = "D653AADE571393B17CF4BF5157A64EBBA0F2D6F2909254CD0E120159E52AECC6";
    };
    "nix-public/org/scala-lang/scala3-sbt-bridge/3.3.7/scala3-sbt-bridge-3.3.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-sbt-bridge/3.3.7/scala3-sbt-bridge-3.3.7-sources.jar";
      sha256 = "C7811196F5CFDD6ABCF271E97000C3957BE8521CB9CFCB38599D9E628E3F5D52";
    };
    "nix-public/org/scala-lang/scala3-sbt-bridge/3.3.7/scala3-sbt-bridge-3.3.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-sbt-bridge/3.3.7/scala3-sbt-bridge-3.3.7.jar";
      sha256 = "3847B6609F800E995D1D1D8F41D591B75EE7397668E0DF1C16DBA4C7C54AA9EB";
    };
    "nix-public/org/scala-lang/scala3-sbt-bridge/3.3.7/scala3-sbt-bridge-3.3.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-sbt-bridge/3.3.7/scala3-sbt-bridge-3.3.7.pom";
      sha256 = "20FBE854BBAC8E8652D0B5BB5EEA66FAC8B431AB694E2BB244AFC6315EF07BF8";
    };
    "nix-public/org/scala-lang/scala3-tasty-inspector_3/3.3.7/scala3-tasty-inspector_3-3.3.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-tasty-inspector_3/3.3.7/scala3-tasty-inspector_3-3.3.7-javadoc.jar";
      sha256 = "CB28915507AF7166275BC45B02879DAB9F0950D3E8ED40A3D75916992C6A4075";
    };
    "nix-public/org/scala-lang/scala3-tasty-inspector_3/3.3.7/scala3-tasty-inspector_3-3.3.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-tasty-inspector_3/3.3.7/scala3-tasty-inspector_3-3.3.7-sources.jar";
      sha256 = "4BEDB504BCC5D921A93CEBFD71249FA049B1295E5842A263F0417C8FD83658C7";
    };
    "nix-public/org/scala-lang/scala3-tasty-inspector_3/3.3.7/scala3-tasty-inspector_3-3.3.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-tasty-inspector_3/3.3.7/scala3-tasty-inspector_3-3.3.7.jar";
      sha256 = "C7594949816C580CCBFA1CB90DED93CF80A56A7E39EE1DE5F5F3AAACEEFDB5BA";
    };
    "nix-public/org/scala-lang/scala3-tasty-inspector_3/3.3.7/scala3-tasty-inspector_3-3.3.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-tasty-inspector_3/3.3.7/scala3-tasty-inspector_3-3.3.7.pom";
      sha256 = "CF03D950328F51E526C07256826C18308CAD815A050FB75E5D2A5BA9176829E2";
    };
    "nix-public/org/scala-lang/scaladoc_3/3.3.7/scaladoc_3-3.3.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scaladoc_3/3.3.7/scaladoc_3-3.3.7-javadoc.jar";
      sha256 = "1A24A4F03BB10350E2FFBBD7BE0FF44FB89AB90A65A022DB7148514A6933B4A3";
    };
    "nix-public/org/scala-lang/scaladoc_3/3.3.7/scaladoc_3-3.3.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scaladoc_3/3.3.7/scaladoc_3-3.3.7-sources.jar";
      sha256 = "0220EA68F7CA45F32A357EEA2252226B8D7CDEED69D102620460692DED163B97";
    };
    "nix-public/org/scala-lang/scaladoc_3/3.3.7/scaladoc_3-3.3.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scaladoc_3/3.3.7/scaladoc_3-3.3.7.jar";
      sha256 = "8115F8ED937FCE7F7C22271C57846C2F35E6BCDAA410C41FD43D5FB4FB1E0DEF";
    };
    "nix-public/org/scala-lang/scaladoc_3/3.3.7/scaladoc_3-3.3.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scaladoc_3/3.3.7/scaladoc_3-3.3.7.pom";
      sha256 = "507D488925419F0EB654790EC0DEFAE27F5C1DBC844DA2CA4A79BA6CFC11AE4D";
    };
    "nix-public/org/scala-lang/tasty-core_3/3.3.7/tasty-core_3-3.3.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/tasty-core_3/3.3.7/tasty-core_3-3.3.7-javadoc.jar";
      sha256 = "D653AADE571393B17CF4BF5157A64EBBA0F2D6F2909254CD0E120159E52AECC6";
    };
    "nix-public/org/scala-lang/tasty-core_3/3.3.7/tasty-core_3-3.3.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/tasty-core_3/3.3.7/tasty-core_3-3.3.7-sources.jar";
      sha256 = "EE9ED10E4C0F3CFDE863FE5588BE5FDB276D71C7D48345A18A5940D9FBFCC5B6";
    };
    "nix-public/org/scala-lang/tasty-core_3/3.3.7/tasty-core_3-3.3.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/tasty-core_3/3.3.7/tasty-core_3-3.3.7.jar";
      sha256 = "0748CD71C48398888313CB3C00B8AAD39BD02F94D43CBCA657D52903517A1E5A";
    };
    "nix-public/org/scala-lang/tasty-core_3/3.3.7/tasty-core_3-3.3.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/tasty-core_3/3.3.7/tasty-core_3-3.3.7.pom";
      sha256 = "D67EE18BAA002E6DC12AEFB8B9F28D817D56BBA1BF683BA4EEA3475CBFB28FDA";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7-javadoc.jar";
      sha256 = "700E5F058F53AD7CB36D4D473F430C6823B81984B21ABEE469A9EAC06F847846";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7-sources.jar";
      sha256 = "6BF753FBA3AFAD192B1837858A2E68D5969976375C27B8E2969CDEA952EFB47F";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7.jar";
      sha256 = "2BACC5761E03920A228E5C9D20B33D9C51D43AAF2F52E8F839ECE630966EB880";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7.pom";
      sha256 = "3B7B0DA8BF5820AA50F4448E19021DE1183164F74A180BD0B68E7D92F3004E31";
    };
    "nix-public/org/scala-sbt/test-interface/1.0/test-interface-1.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0-javadoc.jar";
      sha256 = "A63861B771C20DF0DAB78F26A4FDD573C065FC569DDEF9C907A427B2F57C98A5";
    };
    "nix-public/org/scala-sbt/test-interface/1.0/test-interface-1.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0-sources.jar";
      sha256 = "C314491C9DF4F0BD9DD125EF1D51228D70BD466EE57848DF1CD1B96AEA18A5AD";
    };
    "nix-public/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar";
      sha256 = "15F70B38BB95F3002FEC9AEA54030F19BB4ECFBAD64C67424B5E5FEA09CD749E";
    };
    "nix-public/org/scala-sbt/test-interface/1.0/test-interface-1.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.pom";
      sha256 = "61BA06A9D0C226E10F048004FCEBFB300FDD9B077D05ED502E9875324C8B762E";
    };
    "nix-public/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7-javadoc.jar";
      sha256 = "374E3161D49CA3570F4B454F3229BD8A074E558C90644407E068343C766D5B45";
    };
    "nix-public/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7-sources.jar";
      sha256 = "6AC907710F3BB66A94E2A5D5703AEF5D16DDC1BBAF35185E9F6ACA1354956B12";
    };
    "nix-public/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7.jar";
      sha256 = "1D6B91EFA42B70FC064CAED6D62962374E13B27737F885A87C84C667B30BE625";
    };
    "nix-public/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7.pom";
      sha256 = "D49470C815E070E44F9501116C83F35B179413F5AAFE95E29AC293C67CC16297";
    };
    "nix-public/org/scalacheck/scalacheck_3/1.15.4/scalacheck_3-1.15.4-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalacheck/scalacheck_3/1.15.4/scalacheck_3-1.15.4-javadoc.jar";
      sha256 = "F348AAA92D117701C628BE2ED7C5C04655A090765F02925DAB8B80CF227E9C52";
    };
    "nix-public/org/scalacheck/scalacheck_3/1.15.4/scalacheck_3-1.15.4-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalacheck/scalacheck_3/1.15.4/scalacheck_3-1.15.4-sources.jar";
      sha256 = "9C429B216222C4837C68F0FCD418D76453E6FE18D0D9393FC9D3E00CE0F7501F";
    };
    "nix-public/org/scalacheck/scalacheck_3/1.15.4/scalacheck_3-1.15.4.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalacheck/scalacheck_3/1.15.4/scalacheck_3-1.15.4.jar";
      sha256 = "A344FC84EC8478B9FAF550116DF51E9FFF822448BFE279A05FEC8E16BFAB34E3";
    };
    "nix-public/org/scalacheck/scalacheck_3/1.15.4/scalacheck_3-1.15.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalacheck/scalacheck_3/1.15.4/scalacheck_3-1.15.4.pom";
      sha256 = "3DE696742D97B53A35BF5472DBFC1347D8C07E39B66207E1E8B4EF68E24F6678";
    };
    "nix-public/org/scalactic/scalactic_3/3.2.9/scalactic_3-3.2.9-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_3/3.2.9/scalactic_3-3.2.9-sources.jar";
      sha256 = "AA651F38CED6183C3B2D8881A29863C857F5CB16FF8B56E8621232359878852A";
    };
    "nix-public/org/scalactic/scalactic_3/3.2.9/scalactic_3-3.2.9.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_3/3.2.9/scalactic_3-3.2.9.jar";
      sha256 = "DDE6C79AEB8CA632AC9AEDE0A00462B6B75D0DB857BF0E9F264A2ED36EFCB800";
    };
    "nix-public/org/scalactic/scalactic_3/3.2.9/scalactic_3-3.2.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_3/3.2.9/scalactic_3-3.2.9.pom";
      sha256 = "4F7F0C3A555C1C005CEFCE3145D1C21EE1279E55EAC4D8D4BB2E384513A715CD";
    };
    "nix-public/org/scalatest/scalatest-compatible/3.2.9/scalatest-compatible-3.2.9-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-compatible/3.2.9/scalatest-compatible-3.2.9-javadoc.jar";
      sha256 = "00F91F94F67CE445865357DB5F0A5089CC0217E232BBCF218FB25C8C1FF8E0BD";
    };
    "nix-public/org/scalatest/scalatest-compatible/3.2.9/scalatest-compatible-3.2.9-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-compatible/3.2.9/scalatest-compatible-3.2.9-sources.jar";
      sha256 = "2D2D8645E812F6ACAE111EA36F6F53A970692E8927A2846886A024286538217D";
    };
    "nix-public/org/scalatest/scalatest-compatible/3.2.9/scalatest-compatible-3.2.9.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-compatible/3.2.9/scalatest-compatible-3.2.9.jar";
      sha256 = "7E5F1193AF2FD88C432C4B80CE3641E4B1D062F421D8A0FCC43AF9A19BB7C2EB";
    };
    "nix-public/org/scalatest/scalatest-compatible/3.2.9/scalatest-compatible-3.2.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-compatible/3.2.9/scalatest-compatible-3.2.9.pom";
      sha256 = "79E3EEFA3ED5301FC674545EF4979BD7AA724FF117C155F8B400A1D99F9669E4";
    };
    "nix-public/org/scalatest/scalatest-core_3/3.2.9/scalatest-core_3-3.2.9-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-core_3/3.2.9/scalatest-core_3-3.2.9-sources.jar";
      sha256 = "8530BE3864ECCE0E357B6D08189E73146E7C29A9DE978DF8F8F8402596317849";
    };
    "nix-public/org/scalatest/scalatest-core_3/3.2.9/scalatest-core_3-3.2.9.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-core_3/3.2.9/scalatest-core_3-3.2.9.jar";
      sha256 = "248674B6269578BC2F57D595F1E484FC02837EF567BA461EAFB81294BCE611A8";
    };
    "nix-public/org/scalatest/scalatest-core_3/3.2.9/scalatest-core_3-3.2.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-core_3/3.2.9/scalatest-core_3-3.2.9.pom";
      sha256 = "A901DB445A8BE4459ABFD8B434FEFE7525AA7AEC751CFB9C2A6AFC928A77C285";
    };
    "nix-public/org/scalatest/scalatest-diagrams_3/3.2.9/scalatest-diagrams_3-3.2.9-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-diagrams_3/3.2.9/scalatest-diagrams_3-3.2.9-sources.jar";
      sha256 = "EC87CA9606104FDC5E535FEC602F3A821D16A3C7982CF7D8836E653EEDC58C96";
    };
    "nix-public/org/scalatest/scalatest-diagrams_3/3.2.9/scalatest-diagrams_3-3.2.9.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-diagrams_3/3.2.9/scalatest-diagrams_3-3.2.9.jar";
      sha256 = "20A310D96298A2CDE22E1D990F6EF61320FF38F273902AA31592E04E02D902ED";
    };
    "nix-public/org/scalatest/scalatest-diagrams_3/3.2.9/scalatest-diagrams_3-3.2.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-diagrams_3/3.2.9/scalatest-diagrams_3-3.2.9.pom";
      sha256 = "A59AD711561A43ED957461552BCB3DFCB33C96A5E32B6B8993C1C02589E57D8B";
    };
    "nix-public/org/scalatest/scalatest-featurespec_3/3.2.9/scalatest-featurespec_3-3.2.9-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-featurespec_3/3.2.9/scalatest-featurespec_3-3.2.9-sources.jar";
      sha256 = "C11B1C7DDDBEE2A5724C457CBD403E21A9DFFF047C6FC1372AB671A09FDB03B1";
    };
    "nix-public/org/scalatest/scalatest-featurespec_3/3.2.9/scalatest-featurespec_3-3.2.9.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-featurespec_3/3.2.9/scalatest-featurespec_3-3.2.9.jar";
      sha256 = "DB51DB398582B656CC0B90FBD1C6E5C2495125706B1F860B4CDFC5ABA1832D0D";
    };
    "nix-public/org/scalatest/scalatest-featurespec_3/3.2.9/scalatest-featurespec_3-3.2.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-featurespec_3/3.2.9/scalatest-featurespec_3-3.2.9.pom";
      sha256 = "E814D0292709BD3F01568BD43F46727DDCC0DDF9567C4B00E3C10786E3D23C82";
    };
    "nix-public/org/scalatest/scalatest-flatspec_3/3.2.9/scalatest-flatspec_3-3.2.9-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-flatspec_3/3.2.9/scalatest-flatspec_3-3.2.9-sources.jar";
      sha256 = "B082B6A1401EB5DA9C2DAE5203A70C464F3107D7BBAB7D110E5DC540E9065738";
    };
    "nix-public/org/scalatest/scalatest-flatspec_3/3.2.9/scalatest-flatspec_3-3.2.9.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-flatspec_3/3.2.9/scalatest-flatspec_3-3.2.9.jar";
      sha256 = "B558319F8B4835D25424381DC9B7DCC3B27353CF36DC2C28270DAC59E8C8B827";
    };
    "nix-public/org/scalatest/scalatest-flatspec_3/3.2.9/scalatest-flatspec_3-3.2.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-flatspec_3/3.2.9/scalatest-flatspec_3-3.2.9.pom";
      sha256 = "016D2403CB4B94AE863D00C69A5BBDAC78F1C0F4D59DB9E4B8684445CA45B195";
    };
    "nix-public/org/scalatest/scalatest-freespec_3/3.2.9/scalatest-freespec_3-3.2.9-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-freespec_3/3.2.9/scalatest-freespec_3-3.2.9-sources.jar";
      sha256 = "22B2F75B32D9752E0639C1F1E73627B474CEAC76C42349A5450358ACBF8FE42F";
    };
    "nix-public/org/scalatest/scalatest-freespec_3/3.2.9/scalatest-freespec_3-3.2.9.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-freespec_3/3.2.9/scalatest-freespec_3-3.2.9.jar";
      sha256 = "DFCBCE7D8315DCA731B2829AD233893F2DEC8895543267C086F7C88A618BDA97";
    };
    "nix-public/org/scalatest/scalatest-freespec_3/3.2.9/scalatest-freespec_3-3.2.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-freespec_3/3.2.9/scalatest-freespec_3-3.2.9.pom";
      sha256 = "D5132353445807825314379FCD3D1798800F74E0ADE90573A6EA504D527EDFD9";
    };
    "nix-public/org/scalatest/scalatest-funspec_3/3.2.9/scalatest-funspec_3-3.2.9-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funspec_3/3.2.9/scalatest-funspec_3-3.2.9-sources.jar";
      sha256 = "718C3A582A2DA95B9EFCD88ACD82A0881CF2EDD0B58D651631CA3F0054E918A8";
    };
    "nix-public/org/scalatest/scalatest-funspec_3/3.2.9/scalatest-funspec_3-3.2.9.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funspec_3/3.2.9/scalatest-funspec_3-3.2.9.jar";
      sha256 = "A4D0B15FEA0F73CC7AF7F1E35AE291966F8652FBF811D6525294691FA6FB54D2";
    };
    "nix-public/org/scalatest/scalatest-funspec_3/3.2.9/scalatest-funspec_3-3.2.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funspec_3/3.2.9/scalatest-funspec_3-3.2.9.pom";
      sha256 = "80E827031DF3CB8FD5615BA8CD31897267F4D461E9F5101360ABCA463E09BACB";
    };
    "nix-public/org/scalatest/scalatest-funsuite_3/3.2.9/scalatest-funsuite_3-3.2.9-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funsuite_3/3.2.9/scalatest-funsuite_3-3.2.9-sources.jar";
      sha256 = "E69AC4CABC56AFA995C44C3DB4C8DC1CE9959BB551E8F2040C8EFE0409E3B403";
    };
    "nix-public/org/scalatest/scalatest-funsuite_3/3.2.9/scalatest-funsuite_3-3.2.9.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funsuite_3/3.2.9/scalatest-funsuite_3-3.2.9.jar";
      sha256 = "F3AA7A6414A6F0217AB386BE38DA537738239F073512A00E93967AC34FF3C9D3";
    };
    "nix-public/org/scalatest/scalatest-funsuite_3/3.2.9/scalatest-funsuite_3-3.2.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funsuite_3/3.2.9/scalatest-funsuite_3-3.2.9.pom";
      sha256 = "ACF41471900E231346FF3C29BCA4C60BB855C7AADD495EAE24CFCBF3FDDA41B8";
    };
    "nix-public/org/scalatest/scalatest-matchers-core_3/3.2.9/scalatest-matchers-core_3-3.2.9-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-matchers-core_3/3.2.9/scalatest-matchers-core_3-3.2.9-sources.jar";
      sha256 = "4169A002046D5A3E2F4E2AE895A683F751A28EDCB77376894F0C01D7EB84191E";
    };
    "nix-public/org/scalatest/scalatest-matchers-core_3/3.2.9/scalatest-matchers-core_3-3.2.9.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-matchers-core_3/3.2.9/scalatest-matchers-core_3-3.2.9.jar";
      sha256 = "4AEE69BAF7CBBD2F8C28E02FAB7AEAD12093BF905B322A4ACA9C987DE58DFFAB";
    };
    "nix-public/org/scalatest/scalatest-matchers-core_3/3.2.9/scalatest-matchers-core_3-3.2.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-matchers-core_3/3.2.9/scalatest-matchers-core_3-3.2.9.pom";
      sha256 = "98549F3F560F25D9CA276FC764EB523ADE18C457228DDBC94409978746DE6240";
    };
    "nix-public/org/scalatest/scalatest-mustmatchers_3/3.2.9/scalatest-mustmatchers_3-3.2.9-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-mustmatchers_3/3.2.9/scalatest-mustmatchers_3-3.2.9-sources.jar";
      sha256 = "B790B79C1081C1288E843C932D8392B908942B18A770E4DFC10349946BAEBC34";
    };
    "nix-public/org/scalatest/scalatest-mustmatchers_3/3.2.9/scalatest-mustmatchers_3-3.2.9.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-mustmatchers_3/3.2.9/scalatest-mustmatchers_3-3.2.9.jar";
      sha256 = "2755B8558ACF71603B70D10A02F9DF43A216F305318DBCB442D5451F0DA32C46";
    };
    "nix-public/org/scalatest/scalatest-mustmatchers_3/3.2.9/scalatest-mustmatchers_3-3.2.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-mustmatchers_3/3.2.9/scalatest-mustmatchers_3-3.2.9.pom";
      sha256 = "8A9AD56F68E0C2DADEEA7739E70B49E389EF6FF891EC5406EA580A7162FBA947";
    };
    "nix-public/org/scalatest/scalatest-propspec_3/3.2.9/scalatest-propspec_3-3.2.9-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-propspec_3/3.2.9/scalatest-propspec_3-3.2.9-sources.jar";
      sha256 = "AF07203125A99D97EE8D3659045EEF1C46C9700095EB97E867BBF15116891D4D";
    };
    "nix-public/org/scalatest/scalatest-propspec_3/3.2.9/scalatest-propspec_3-3.2.9.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-propspec_3/3.2.9/scalatest-propspec_3-3.2.9.jar";
      sha256 = "BAE00B7CE007B8CC86FFDDB44246F5AA8E47055414337DDF322A9AE7C95EA809";
    };
    "nix-public/org/scalatest/scalatest-propspec_3/3.2.9/scalatest-propspec_3-3.2.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-propspec_3/3.2.9/scalatest-propspec_3-3.2.9.pom";
      sha256 = "B0FA28BFEC25845D40875AEA6C082FC588F68B78C536FFA33256FF6D795ED7E2";
    };
    "nix-public/org/scalatest/scalatest-refspec_3/3.2.9/scalatest-refspec_3-3.2.9-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-refspec_3/3.2.9/scalatest-refspec_3-3.2.9-sources.jar";
      sha256 = "9F6AE34B3B04B664CFCD1EBDCA02E78A3FAD1DBEA1BA634E7464375553CC874F";
    };
    "nix-public/org/scalatest/scalatest-refspec_3/3.2.9/scalatest-refspec_3-3.2.9.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-refspec_3/3.2.9/scalatest-refspec_3-3.2.9.jar";
      sha256 = "3F7A1CAB9D46D6F57C694E0DDC65DB009F7CD0951BBF3A3C3A660C2F52A28DEE";
    };
    "nix-public/org/scalatest/scalatest-refspec_3/3.2.9/scalatest-refspec_3-3.2.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-refspec_3/3.2.9/scalatest-refspec_3-3.2.9.pom";
      sha256 = "3433A659FE2CE0D99B1D805BBC178DCF1250BAC36B5CBEB415227925DFA27ADA";
    };
    "nix-public/org/scalatest/scalatest-shouldmatchers_3/3.2.9/scalatest-shouldmatchers_3-3.2.9-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-shouldmatchers_3/3.2.9/scalatest-shouldmatchers_3-3.2.9-sources.jar";
      sha256 = "88AB41BAAF46BCE9E8BA83AF969F44F8F0B90AE2F8C4B627F9AE857D7A759E86";
    };
    "nix-public/org/scalatest/scalatest-shouldmatchers_3/3.2.9/scalatest-shouldmatchers_3-3.2.9.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-shouldmatchers_3/3.2.9/scalatest-shouldmatchers_3-3.2.9.jar";
      sha256 = "5866C9F28FAF5389A82D0A66F3539933325EED3A03425C9BF2F495C34F4BB370";
    };
    "nix-public/org/scalatest/scalatest-shouldmatchers_3/3.2.9/scalatest-shouldmatchers_3-3.2.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-shouldmatchers_3/3.2.9/scalatest-shouldmatchers_3-3.2.9.pom";
      sha256 = "B7E416B6F194451142CE114306731E907D0DFE7CB48C86CAEBC6ABE09C31DBEF";
    };
    "nix-public/org/scalatest/scalatest-wordspec_3/3.2.9/scalatest-wordspec_3-3.2.9-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-wordspec_3/3.2.9/scalatest-wordspec_3-3.2.9-sources.jar";
      sha256 = "0A9FF731CFDC2F9ED554695BEB8CF7860D44F952C639B91B0146DDC8D54F6491";
    };
    "nix-public/org/scalatest/scalatest-wordspec_3/3.2.9/scalatest-wordspec_3-3.2.9.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-wordspec_3/3.2.9/scalatest-wordspec_3-3.2.9.jar";
      sha256 = "28A649D8F73FBD7A9D02E702A5F23577B4F6E301840D002D5574728A6BA5C473";
    };
    "nix-public/org/scalatest/scalatest-wordspec_3/3.2.9/scalatest-wordspec_3-3.2.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-wordspec_3/3.2.9/scalatest-wordspec_3-3.2.9.pom";
      sha256 = "F67D4A98E5CE9D62D5021FDB3EDF2FD093FC5E2F213E67E6B3268AA922F4B157";
    };
    "nix-public/org/scalatest/scalatest_3/3.2.9/scalatest_3-3.2.9-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_3/3.2.9/scalatest_3-3.2.9-sources.jar";
      sha256 = "52C0E45790728595A64DE39C298A12B6870A60F04AFFE0146BE458F73D771EED";
    };
    "nix-public/org/scalatest/scalatest_3/3.2.9/scalatest_3-3.2.9.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_3/3.2.9/scalatest_3-3.2.9.jar";
      sha256 = "6A528ED38912F9C69BF2A1BE157871FE801BBFF590EECB1A56FA25C62570E147";
    };
    "nix-public/org/scalatest/scalatest_3/3.2.9/scalatest_3-3.2.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_3/3.2.9/scalatest_3-3.2.9.pom";
      sha256 = "62C199FAE3085D79512464713ED432187349EAA90B154020F7F45485B86F64B4";
    };
    "nix-public/org/scalatestplus/scalacheck-1-15_3/3.2.9.0/scalacheck-1-15_3-3.2.9.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatestplus/scalacheck-1-15_3/3.2.9.0/scalacheck-1-15_3-3.2.9.0-sources.jar";
      sha256 = "9F0F9208E8290E106338F997D8B01D27409333BE225ABDC91926776B10E7DBB0";
    };
    "nix-public/org/scalatestplus/scalacheck-1-15_3/3.2.9.0/scalacheck-1-15_3-3.2.9.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatestplus/scalacheck-1-15_3/3.2.9.0/scalacheck-1-15_3-3.2.9.0.jar";
      sha256 = "E893F07E81C2ADAF61D03ABDDDCB67E1F81883522132FCE52003B50325B92D94";
    };
    "nix-public/org/scalatestplus/scalacheck-1-15_3/3.2.9.0/scalacheck-1-15_3-3.2.9.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatestplus/scalacheck-1-15_3/3.2.9.0/scalacheck-1-15_3-3.2.9.0.pom";
      sha256 = "A6D383359F671ECAB06F28612A2A55DFF4DB0F5F45622CC7943A427F6CE7E8C9";
    };
    "nix-public/org/scodec/scodec-bits_3/1.1.34/scodec-bits_3-1.1.34-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scodec/scodec-bits_3/1.1.34/scodec-bits_3-1.1.34-javadoc.jar";
      sha256 = "C8750F2D5D5BA16F9C3A3F1DBAECBC2FDD9012DE17A01D3DC08B1A579EEBDD13";
    };
    "nix-public/org/scodec/scodec-bits_3/1.1.34/scodec-bits_3-1.1.34-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scodec/scodec-bits_3/1.1.34/scodec-bits_3-1.1.34-sources.jar";
      sha256 = "687D2BF0EA9905BD6FCC8696D35770DFDB049AB266292B1F4CECB64E166EE549";
    };
    "nix-public/org/scodec/scodec-bits_3/1.1.34/scodec-bits_3-1.1.34.jar" = {
      url = "https://repo1.maven.org/maven2/org/scodec/scodec-bits_3/1.1.34/scodec-bits_3-1.1.34.jar";
      sha256 = "E8845F4F0CA3F59895BD903BC3D92D59ADF258411D9B60A189F2CE03F351C5F1";
    };
    "nix-public/org/scodec/scodec-bits_3/1.1.34/scodec-bits_3-1.1.34.pom" = {
      url = "https://repo1.maven.org/maven2/org/scodec/scodec-bits_3/1.1.34/scodec-bits_3-1.1.34.pom";
      sha256 = "71CF79EEDA21ADFF17814E22A6F3B76868A120F2C4574B40DBBD29DB330C7255";
    };
    "nix-public/org/sonatype/oss/oss-parent/9/oss-parent-9.pom" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom";
      sha256 = "FB40265F982548212FF82E362E59732B2187EC6F0D80182885C14EF1F982827A";
    };
    "nix-public/org/yaml/snakeyaml/2.0/snakeyaml-2.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/yaml/snakeyaml/2.0/snakeyaml-2.0-javadoc.jar";
      sha256 = "C5D4C8904A5B2EC1572FD8EF3EEC86013EDC3533ED6D929159ABFBF53E3B552E";
    };
    "nix-public/org/yaml/snakeyaml/2.0/snakeyaml-2.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/yaml/snakeyaml/2.0/snakeyaml-2.0-sources.jar";
      sha256 = "9B336F77718EE80225D3D878FE5AB753E9863614FB84E3E859D51432DDE43199";
    };
    "nix-public/org/yaml/snakeyaml/2.0/snakeyaml-2.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/yaml/snakeyaml/2.0/snakeyaml-2.0.jar";
      sha256 = "880C9D896E4B74A06C549C15CA496450165D6909FA15D7E662BEE8F6A66D7AFA";
    };
    "nix-public/org/yaml/snakeyaml/2.0/snakeyaml-2.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/yaml/snakeyaml/2.0/snakeyaml-2.0.pom";
      sha256 = "43C761F92B549C8B08FB992080253E49F0A983E544EF0663C1F4F9D68EB52616";
    };
    "nix-public/ua/co/k/strftime4j/1.0.5/strftime4j-1.0.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/ua/co/k/strftime4j/1.0.5/strftime4j-1.0.5-javadoc.jar";
      sha256 = "4574900538CCA041C62DEFE1A889E5DC8092C8118C554C7548ECAE344A1CB17C";
    };
    "nix-public/ua/co/k/strftime4j/1.0.5/strftime4j-1.0.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/ua/co/k/strftime4j/1.0.5/strftime4j-1.0.5-sources.jar";
      sha256 = "33A2CC43EEE1C2C1C3A57E68783B5B93CA05041C1505E67799DA43B0595E966C";
    };
    "nix-public/ua/co/k/strftime4j/1.0.5/strftime4j-1.0.5.jar" = {
      url = "https://repo1.maven.org/maven2/ua/co/k/strftime4j/1.0.5/strftime4j-1.0.5.jar";
      sha256 = "8EE3BE181A1D3871D2B14E1E145CBC48918ABBBF3596268FDD4B3D7292B07FC9";
    };
    "nix-public/ua/co/k/strftime4j/1.0.5/strftime4j-1.0.5.pom" = {
      url = "https://repo1.maven.org/maven2/ua/co/k/strftime4j/1.0.5/strftime4j-1.0.5.pom";
      sha256 = "DF50D06823A4F87C3FD739EBD1718F09BC126BB8206DFDE8C477B3A816EDF500";
    };
  };
}